= HelloWorld

The project is the first of many in our new open-source drive.

== Installation and Getting Started
The project is a standard HelloWorld example using spring-boot.

Here is a quick view of our complete code:

[source,java,indent=0]
----
    package ba.oss;

    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;
    import org.springframework.boot.CommandLineRunner;
    import org.springframework.boot.SpringApplication;
    import org.springframework.boot.autoconfigure.SpringBootApplication;

    @SpringBootApplication
    public class HelloworldApplication implements CommandLineRunner{

        private static final Logger log = LoggerFactory.getLogger(HelloworldApplication.class);

        @Override
        public void run(String... strings) throws Exception {
            log.info("Barclays Africa: Hello to the open source world");
        }

        public static void main(String[] args) {
            SpringApplication.run(HelloworldApplication.class, args);
        }
    }
----

== Getting help & reporting issues
Our project uses GitHub's integrated issue tracking system to record bugs and feature
requests. If you want to raise an issue, please follow the recommendations below:

* Report bugs with our app at https://github.com/BarclaysAfrica/helloworld/issues[github.com/BarclaysAfrica/helloworld/issues].

== Running the project
Ensure you have http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java8 JDK] installed and added to environment path.
You do not require Maven to be installed if you use the `mvnw` scripts to run the project as a local instance of Maven will be downloaded automatically.
However, if you intend building the project you will require https://maven.apache.org/download.cgi[Maven v3.0.5 or above].

To run the project:

[indent=0]
----
    $ git clone https://github.com/BarclaysAfrica/helloworld
    $ cd helloworld
	$ ./mvnw # Windows users use mvnw.cmd
----

== License
This project is released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
